#! /bin/sh

. /etc/tslib-env.sh
. /etc/qtopia-env.sh

# 1 running starter-dialog
/opt/Qtopia/bin/starter-dialog -qws >/dev/console </dev/console

# 2 running paladin

#export SDL_NOMOUSE=1
export SDL_MOUSEDRV=TSLIB
export SDL_MOUSEDEV=/dev/touchscreen-1wire

#cat /sys/class/graphics/fb0/virtual_size,modes

cd /opt/paladin/
exec ./run-sdlpal -w 800 -h 480  >/dev/console </dev/console

#./run-sdlpal -w 800 -h 480  2>&1 >/dev/console
#
#killall -9 qpe
#killall -9 quicklauncher
#killall -9 qss
#qpe 2>&1 >/dev/console &

