/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Build Parameters
 */
#undef CONFIG_TARGET_X86
#define CONFIG_TARGET_OPENWRT 1
#undef CONFIG_TARGET_MACOSX
#undef CONFIG_TARGET_SHARP
#undef CONFIG_TARGET_C700
#undef CONFIG_TARGET_OE
#undef CONFIG_TARGET_IPAQ
#undef CONFIG_TARGET_RAMSES
#undef CONFIG_TARGET_SIMPAD
#undef CONFIG_TARGET_YOPY
#undef CONFIG_TARGET_HTC
#undef CONFIG_TARGET_64BIT
#undef CONFIG_OPTIMIZE
#undef CONFIG_THREADED
#undef CONFIG_STATIC
#undef CONFIG_DEBUG
#define CONFIG_RELEASE 1
#define CONFIG_QUICK_LAUNCH 1
#define CONFIG_QUICKLAUNCH_PATH "/opt/QtPalmtop/bin/quicklauncher"
#define CONFIG_SPECFILE "qws/linux-openwrt-g++"
#define CONFIG_CUSTOMFILE "custom-openwrt.h"
#define CONFIG_EXPERIMENTAL 1
#define CONFIG_USE_CCACHE 1

/*
 * Configuration
 */
#undef CONFIG_OPIE_NO_BUILTIN_SHUTDOWN
#undef CONFIG_OPIE_NO_BUILTIN_CALIBRATE
#define CONFIG_OPIE_SOUND_FRAGMENT_SHIFT "16"
#undef CONFIG_USE_REALTIME_AUDIO_THREAD
#define CONFIG_USE_FILE_NOTIFICATION 1
#undef CONFIG_OPIE_NEW_ALLOC
#undef CONFIG_OPIE_TASKBAR_LOCK_KEY_STATE
#define CONFIG_LIBQPE_WITHROHFEEDBACK 1
#undef CONFIG_LIBQPE_NO_INLINE_IMAGES
#undef CONFIG_OPIE_NO_SOUND_PCM_READ_BITS

/*
 * Dependencies
 */
#define CONFIG_LIBETPAN_DEP 1
#define CONFIG_LIBETPAN_LIB_DIR ""
#define CONFIG_LIBETPAN_INC_DIR ""
#define CONFIG_LIBPCAP_DEP 1
#define CONFIG_LIBPCAP_LIB_DIR ""
#define CONFIG_LIBPCAP_INC_DIR ""
#define CONFIG_LIBSQLITE_DEP 1
#define CONFIG_LIBSQLITE_LIB_DIR ""
#define CONFIG_LIBSQLITE_INC_DIR ""
#define CONFIG_LIBXINE_DEP 1
#define CONFIG_LIBXINE_LIB_DIR ""
#define CONFIG_LIBXINE_INC_DIR ""
#define CONFIG_LIBOPK_DEP 1
#undef CONFIG_LIBIPK_DEP
#define CONFIG_LIBIPK_LIB_DIR ""
#define CONFIG_LIBIPK_INC_DIR ""
#define CONFIG_LIBSDL_DEP 1
#define CONFIG_LIBSDL_LIB_DIR ""
#define CONFIG_LIBSDL_INC_DIR ""
#define CONFIG_LIBSWORD_DEP 1
#define CONFIG_LIBSWORD_LIB_DIR ""
#define CONFIG_LIBSWORD_INC_DIR ""
#define CONFIG_LIBBLUEZ_DEP 1
#define CONFIG_LIBBLUEZ_LIB_DIR ""
#define CONFIG_LIBBLUEZ_INC_DIR ""
#define CONFIG_LIBFREETYPE2_DEP 1
#define CONFIG_LIBFREETYPE2_INC_DIR ""
#define CONFIG_LIBFLITE_DEP 1
#define CONFIG_LIBFLITE_INC_DIR ""
#define CONFIG_LIBFLITE_LIB_DIR ""
#define CONFIG_LIBOBEXFTP_DEP 1
#define CONFIG_LIBOBEXFTP_INC_DIR ""
#define CONFIG_LIBOBEXFTP_LIB_DIR ""

/*
 * Base
 */
#define CONFIG_LIBQPE 1
#undef CONFIG_X11

/*
 * 
 */
#define CONFIG_LIBOPIE2CORE 1
#define CONFIG_LIBOPIE2DB 1
#define CONFIG_LIBOPIE2NET 1
#define CONFIG_LIBOPIE2PIM 1
#define CONFIG_SQL_PIM_BACKEND 1
#define CONFIG_LIBOPIE2UI 1
#define CONFIG_LIBOPIE2MM 1
#define CONFIG_LIBOPIE2SECURITY 1
#define CONFIG_LIBOPIE2BLUEZ 1

/*
 * 
 */
#define CONFIG_LIBQTAUX 1
#define CONFIG_LIBQRSYNC 1
#define CONFIG_OPIE-LOGIN 1
#undef CONFIG_OPIELOGIN_USEPAM
#define CONFIG_OPIEALARM 1
#define CONFIG_QUICKLAUNCHER 1
#define CONFIG_HOTPLUG_QCOP 1
#define CONFIG_LAUNCHER 1
#define CONFIG_SYMLINKER 1

/*
 * 
 */

/*
 * Applets
 */
#define CONFIG_ABOUTAPPLET 1
#define CONFIG_BATTERYAPPLET 1
#define CONFIG_PCMCIA-APPLET 1
#define CONFIG_CLIPBOARDAPPLET 1
#define CONFIG_CLOCKAPPLET 1
#define CONFIG_HOMEAPPLET 1
#define CONFIG_IRDAAPPLET 1
#define CONFIG_LOCKAPPLET 1
#define CONFIG_LOGOUTAPPLET 1
#define CONFIG_MULTIKEYAPPLET 1
#define CONFIG_RESTARTAPPLET 1
#define CONFIG_ROTATEAPPLET 1
#define CONFIG_SCREENSHOTAPPLET 1
#define CONFIG_SUSPENDAPPLET 1
#define CONFIG_VMEMO 1
#define CONFIG_VOLUMEAPPLET 1
#define CONFIG_VTAPPLET 1
#define CONFIG_AUTOROTATEAPPLET 1
#undef CONFIG_BRIGHTNESSAPPLET
#define CONFIG_CARD-APPLET 1
#undef CONFIG_KEYHELPER
#define CONFIG_MEMORYAPPLET 1
#undef CONFIG_NETWORKAPPLET
#define CONFIG_NOTESAPPLET 1
#undef CONFIG_PYQUICKLAUNCH
#undef CONFIG_VOLUMEAPPLET2
#define CONFIG_WIRELESSAPPLET 1
#define CONFIG_ZKBAPPLET 1

/*
 * Apps
 */
#define CONFIG_CALIBRATE 1
#define CONFIG_EMBEDDEDKONSOLE 1
#define CONFIG_HELPBROWSER 1
#define CONFIG_OAPP 1
#define CONFIG_QCOP 1
#define CONFIG_QSS 1
#define CONFIG_TABOAPP 1
#define CONFIG_TEXTEDIT 1
#define CONFIG_ADVANCEDFM 1
#define CONFIG_CHECKBOOK 1
#define CONFIG_CONFEDIT 1
#define CONFIG_DAGGER 1
#define CONFIG_ODICT 1
#define CONFIG_BARTENDER 1
#define CONFIG_OPIE-CONSOLE 1
#define CONFIG_GUTENBROWSER 1
#define CONFIG_OPIE-READER 1
#define CONFIG_OPIE-READER-FLITEDYN 1
#define CONFIG_OPIE-READER-FLITEDYN16 1
#define CONFIG_OPIE-SHEET 1
#define CONFIG_OPIE-WRITE 1
#define CONFIG_OXYGEN 1
#define CONFIG_TABLEVIEWER 1
#define CONFIG_TINYKATE 1
#define CONFIG_ZSAFE 1

/*
 * Communications and Networking
 */
#define CONFIG_KEYPEBBLE 1
#define CONFIG_FTPLIB 1
#define CONFIG_LIBMAILWRAPPER 1
#define CONFIG_MAIL3 1
#define CONFIG_MAILAPPLET 1
#undef CONFIG_OPIESMB
#define CONFIG_OPIEFTP 1
#define CONFIG_OPIEIRC 1
#undef CONFIG_OPIE-RDESKTOP
#define CONFIG_OPIESTUMBLER 1
#undef CONFIG_OPIETOOTH
#define CONFIG_WELLENREITER 1

/*
 * Games
 */
#define CONFIG_BACKGAMMON 1
#define CONFIG_BOUNCE 1
#define CONFIG_BUZZWORD 1
#define CONFIG_FIFTEEN 1
#define CONFIG_GO 1
#define CONFIG_KBILL 1
#define CONFIG_KCHECKERS 1
#define CONFIG_KPACMAN 1
#define CONFIG_MINDBREAKER 1
#define CONFIG_MINESWEEP 1
#define CONFIG_YATZEE 1
#define CONFIG_PARASHOOT 1
#define CONFIG_QASTEROIDS 1
#define CONFIG_SFCAVE 1
#undef CONFIG_SFCAVE-SDL
#define CONFIG_SNAKE 1
#define CONFIG_SOLITAIRE 1
#define CONFIG_TETRIX 1
#define CONFIG_TICTAC 1
#define CONFIG_WORDGAME 1
#define CONFIG_ZLINES 1
#define CONFIG_ZSAME 1

/*
 * Graphics and Multimedia
 */
#define CONFIG_FREETYPE 1
#define CONFIG_DRAWPAD 1
#define CONFIG_OPIE_EYE 1
#define CONFIG_OPIE_EYE_SLAVE 1
#define CONFIG_OPIEPLAYER 1
#define CONFIG_LIBMAD 1
#define CONFIG_LIBMPEG3 1
#define CONFIG_MODPLUG 1
#define CONFIG_WAVPLUGIN 1
#define CONFIG_LIBTREMOR 1
#define CONFIG_LIBTREMORPLUGIN 1
#define CONFIG_CAMERA 1
#define CONFIG_CAMERA2 1
#define CONFIG_OPIEPLAYER2 1
#define CONFIG_OPIEREC 1
#define CONFIG_POWERCHORD 1
#define CONFIG_TONLEITER 1

/*
 * Input methods
 */
#define CONFIG_DVORAK 1
#define CONFIG_HANDWRITING 1

/*
 * opie-handwriting-classicset automatically selected
 */

/*
 * opie-handwriting-graffitiset automatically selected
 */
#define CONFIG_JUMPX 1
#define CONFIG_KEYBOARD 1
#define CONFIG_KJUMPX 1
#define CONFIG_MULTIKEY 1
#define CONFIG_PICKBOARD 1
#define CONFIG_UNIKEYBOARD 1

/*
 * Pim
 */
#define CONFIG_OBEX 1
#define CONFIG_ADDRESSBOOK 1
#define CONFIG_DATEBOOK 1
#define CONFIG_NOTES 1
#define CONFIG_OSEARCH 1
#define CONFIG_TODAY 1
#define CONFIG_TODO 1

/*
 * Today Plugins ---
 */
#define CONFIG_TODAY_FORTUNE 1
#define CONFIG_TODAY_STOCKTICKER 1
#define CONFIG_TODAY_STOCKTICKERSUB 1
#define CONFIG_TODAY_STOCKTICKERLIB 1
#define CONFIG_TODAY_WEATHER 1
#define CONFIG_TODAY_ADDRESSBOOK 1
#define CONFIG_TODAY_DATEBOOK 1
#define CONFIG_TODAY_MAIL 1
#define CONFIG_TODAY_TODOLIST 1

/*
 * Holiday Plugins ---
 */

/*
 * Holiday Plugins
 */
#define CONFIG_DATEBOOK_BIRTHDAYS_PLUGIN 1
#define CONFIG_DATEBOOK_CHRISTIAN_PLUGIN 1
#define CONFIG_DATEBOOK_NATIONAL_HOLIDAY 1

/*
 * Settings
 */
#define CONFIG_BUTTON-SETTINGS 1
#define CONFIG_CITYTIME 1
#define CONFIG_LAUNCHER-SETTINGS 1
#define CONFIG_LIGHT-AND-POWER 1
#define CONFIG_SECURITY 1
#undef CONFIG_MULTIAUTH_DEMO
#define CONFIG_APPEARANCE2 1
#define CONFIG_AQPKG 1
#define CONFIG_BACKUP 1
#define CONFIG_DOCTAB 1
#undef CONFIG_KBDDCONTROL
#undef CONFIG_KBDDAPPLET
#define CONFIG_LANGUAGE 1
#define CONFIG_MEDIUMMOUNT 1
#define CONFIG_NETSYSTEMTIME 1
#define CONFIG_NETWORKSETUP 1
#define CONFIG_NETWORKSETUP-CORE 1
#define CONFIG_PPP 1
#define CONFIG_WLAN 1
#define CONFIG_INTERFACES 1
#define CONFIG_NS2CORE 1
#define CONFIG_NS2OPIETOOTH 1
#define CONFIG_NS2OPIETOOTHAPPLET 1
#define CONFIG_NS2 1
#undef CONFIG_NS2PROFILE
#undef CONFIG_NS2NETWORK
#undef CONFIG_NS2LANCARD
#undef CONFIG_NS2PPP
#undef CONFIG_NS2WLAN
#undef CONFIG_NS2USB
#undef CONFIG_NS2IRDA
#undef CONFIG_NS2VPN
#undef CONFIG_NS2BT
#undef CONFIG_NS2CABLE
#undef CONFIG_NS2MODEM
#undef CONFIG_NS2GPRS
#define CONFIG_PACKAGEMANAGER 1
#define CONFIG_SOUND 1
#define CONFIG_SSHKEYS 1
#define CONFIG_SYSINFO 1
#define CONFIG_MULTIAUTH_BLUEPING 1
#define CONFIG_MULTIAUTH_DUMMY 1
#define CONFIG_MULTIAUTH_NOTICE 1
#define CONFIG_MULTIAUTH_PIN 1

/*
 * Theming
 */

/*
 * Decorations ---
 */

/*
 * Decorations
 */
#define CONFIG_DECO_FLAT 1
#define CONFIG_DECO_LIQUID 1
#define CONFIG_DECO_POLISHED 1

/*
 * Styles ---
 */

/*
 * Styles
 */
#define CONFIG_FLAT 1
#define CONFIG_FRESH 1
#define CONFIG_LIQUID 1
#define CONFIG_METAL 1
#undef CONFIG_PHASE
#define CONFIG_THEME 1
#undef CONFIG_WEBSTYLE

/*
 * Tools
 */
#define CONFIG_CALCULATOR 1
#define CONFIG_CLOCK 1
#define CONFIG_EUROCONV 1
#define CONFIG_FORMATTER 1
#define CONFIG_OPIE-SH 1
#undef CONFIG_PIMCONVERTER
#undef CONFIG_PYQUICKLAUNCHER
#define CONFIG_REMOTE 1

/*
 * Development
 */
#define CONFIG_KEYVIEW 1

/*
 * Examples
 */
#undef CONFIG_EXAMPLES

/*
 * 
 */

/*
 * Unsupported / Unmaintained
 */
#define CONFIG_SHOWIMG 1
#define CONFIG_TABMANAGER 1
#define CONFIG_UBROWSER 1
#define CONFIG_USERMANAGER 1
#undef CONFIG_QWS
